### ISSUE TITLE
Support User-Agent Client Hints

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/relay#1183]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account

## Package + Version

- [X] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:
```
6.17.9
```

## Description
Sentry seems to be capturing the Windows 11 platform as Windows 10.

Sample code:
```javascript
<script>
Sentry.init({
  dsn: "https://d16ae2d36f9249849c7964e9a3a8a608@o447951.ingest.sentry.io/5429213",
});
Sentry.CaptureMessage("Hello World");
</script>
```
Sample event:
https://sentry.io/organizations/sentry-sdks/issues/3024003271/events/0e4c3c7c7de840a889b18d67ca15e473/?project=5429213

**Comment by AbhiPrasad** [comment]
This is being grabbed from the user-agent, and relay actually populates the browser value based on the user-agent of the client that sent the event.

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.55`

Interesting - it seems like Windows team made it so that user agents are frozen on Windows 10, and you need to use User-Agent Client Hints to check if it's coming from Windows 11. https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

I've raised a ticket internally as it seems Relay does not support https://wicg.github.io/ua-client-hints/, and will transfer this ticket to the Relay repo to track there.

**Comment by AbhiPrasad** [comment]
Obsolete Sentry internal JIRA ticket: https://getsentry.atlassian.net/browse/INGEST-1422

**Comment by AbhiPrasad** [comment]
Sentry internal DACI: https://www.notion.so/sentry/Handling-of-new-client-hints-to-parse-user-agent-information-3590fcbbdbd542faa6fa07ba67c0ddb3

**Comment by jan-auer** [comment]
Acceptance criteria that was discussed about this internally:

- Generally, everything here applies both to user agent parsing from request headers of the store request, and user agent headers from within the event JSON.
- If any client hint header is present, the User-Agent header is not trustworthy and should not be used for parsing. Instead client hints should be used to extract os/browser information.
- We will lose information about the OS version, which means there may be downstream changes we need to make in derived tags and the UI to still show OS-without-a-version correctly.
- The OS version can still be provided by adding a `<meta>` tag. Add a new docs page for all platforms that explains the situation and what code the customer needs to inject into their pages. There’s two cases to document: One for HTTP requests from the frontend going to the store endpoint, and one for HTTP requests going from the frontend to the backend.
- We need UI updates to link to the relevant docs page in case the OS name is there, but the version is missing.
- There are no changes to the event protocol.
- No proactive communication about this change is required.

**Comment by TBS1996** [comment]
- [x] https://github.com/getsentry/relay/pull/1752
- [x] https://github.com/getsentry/relay/pull/1802 
- [ ] Make necessary changes due to losing OS-version information
- [ ] UI updates to link to the relevant docs page in case the OS name is there, but the version is missing.
