### ISSUE TITLE
Allow configuring extra HTTP response headers 

### ISSUE THREAD

**Issue by schmkr** [getsentry/relay#1335]
The relay proxy is a great addition to the Sentry setup that allows us to do the scrubbing within our own infra before sending it to for further processing.

Various automated scans, also check the domains we host the rely proxy on and automatically report that domain as insecure because of various missing headers from the server responses.

Would it be possible, to allow configuring the proxy to add security headers to the responses to clients?

Headers like:
- HSTS (`Strict-Transport-Security`)
- `Referrer-Policy`
- `X-Frame-Options`
- `X-Content-Type-Options`
- `X-Permitted-Cross-Domain-Policies`
- `X-XSS-Protection`

I'm well aware most of these headers wouldn't _actually_ protect against any risks for the urls served by the relay proxy. But it's sometimes hard (or at least exhausting) to have to explain to auditors or other folks that ran an automated test against your domain, why the lack of those headers is not an issue.

**Comment by iker-barriocanal** [comment]
Hey @schmkr, have you considered adding your own proxy in front of it?

**Comment by schmkr** [comment]
Hi @iker-barriocanal, yes we have. We could do something like that, but would rather keep the setup as simple/flat as possible. So if it would be possible, that would be great. If not, we would have to add yet another proxy, yes.

**Comment by iker-barriocanal** [comment]
Since the issue is originally coming from explaining to your auditors why these headers are missing in your services, I'd suggest you add a proxy in front of relay to have full flexibility on what headers are managed. This approach also provides more flexibility to update the set of headers as your requirements evolve without relying on Sentry to manage them, besides the security benefits a proxy provides.

Thanks for your feedback, but I'll be closing this issue as there are no plans to pursue this in the near future.
