### ISSUE TITLE
Relay connect to kafka with ssl auth

### ISSUE THREAD

**Issue by bumarcell** [getsentry/relay#1361]
We are using Sentry on-premise on Kubernetes ([this helm chart](https://github.com/sentry-kubernetes/charts)) with external Kafka. Our production Kafka uses ssl authentication, which I think is a common practice.

I noticed this feature was requested (and implemented) 2 years ago [here](https://github.com/getsentry/relay/issues/879) however it was reverted due to some regression problem (and the feature being regarded as an "edge case")  

Would it still be problematic to implement it with the current Sentry/Relay version 2 years after?

**Comment by untitaker** [comment]
@bumarcell feel free to come up with a solution that solves the concern of not being able to use `--all-features`: https://github.com/getsentry/relay/pull/889

The concrete problem: We want to be able to run `cargo build --all-features` on macos, which is our primary development platform. The initial implementation broke that because the new `kafka-ssl` feature didn't compile on macos (iirc). I don't think we would object to additional, mandatory dependencies for as long as they're easy to manage (i.e.: they compile on macos).

We're calling it an "edge case" in that we're not going to try and spend more time on implementing this but I don't think we'd reject a patch that reintroduces this with those problems fixed.
