### ISSUE TITLE
Increase character limit for the logger

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/relay#1827]
A customer gets it's value from the logger but it's been capped at 64 which truncates the information.
Is there a reason for this or can we up the limit to a fair amount like for instance the TagValue => 200

`"_meta": {
    "logger": {
      "": {
        "rem": [
          [
            "!limit",
            "s",
            61,
            64
          ]
        ],
        "len": 86
      }
    }
  },`

can be found in this [file ](https://github.com/getsentry/relay/blob/6ebaf355ef20a2c10c5d1ced99f5a296b31c396c/relay-general/src/processor/attrs.rs#L117-L138)

**Comment by benoit-lateltin** [comment]
Thank you for considering this.
In Java, most of the time the logger name is generated from the class name. It can be pretty long because it is a fully qualified name including the package before the actual class name. 

Example: `com.company.project.module.layer.subpackage.category.BusinessEntityErrorResolver`

If you have to truncate this value, maybe it would make more sense to keep the class name at the end and truncate the beginning (fully qualified name is always better). 

Should this be implemented in `sentry-logback` and `sentry-log4j` because it seems specific to Java logging frameworks?

**Comment by olksdr** [comment]
* Check the Sentry side if there are any limitation on `logger` field as well

**Comment by olksdr** [comment]
@benoit-lateltin  it sounds like a good idea. 

Could you, please, also open the issue  (feature request) in https://github.com/getsentry/sentry-java ?

**Comment by iker-barriocanal** [comment]
After an internal conversation, we'll trim from the beginning of the string instead, keeping the max at 64 unicode chars.

**Comment by benoit-lateltin** [comment]
Make sense @iker-barriocanal 👌 

@olksdr Do I still need to open the issue in https://github.com/getsentry/sentry-java? (I haven't done it yet 🙁)

**Comment by iker-barriocanal** [comment]
@benoit-lateltin no, that won't be necessary. This is something that will happen in relay, no SDK changes are required.

**Comment by jan-auer** [comment]
We can detect class paths during trimming and apply some better trimming logic for these, e.g. trim at `.` boundaries.
