### ISSUE TITLE
Keep frames closest to crash

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1980]
The `TrimmingProcessor` keeps the first 249 frames in a stack trace, plus the last frame in the stack trace. This means that we prioritize frames far away from the crash, and drop frames that are close to the crash:

> The list is ordered from caller to callee [...] The last frame is the one creating the exception.

https://develop.sentry.dev/sdk/event-payloads/stacktrace/#attributes

https://github.com/getsentry/relay/blob/35f5d8627b3de1749b25c31ff1b94c7a9833c6ad/relay-general/src/store/trimming.rs#L326-L339

Unless Relay inverts the entire list at some point before calling this function, this means that the frames closest to the crash are trimmed (except the one closest to it).

Consider trimming from the start instead.

**Comment by jjbayer** [comment]
cc @Swatinem

**Comment by Swatinem** [comment]
This is related to https://github.com/getsentry/sentry-rust/issues/470#issuecomment-1472136215
We have such a large number of frames because of exponential explosion here: https://github.com/getsentry/sentry/issues/46435

But even then, we should rather trim the bottom and not the top, so customers are not quite as confused.
