### ISSUE TITLE
Default data scrubbers not scrubbing tag value

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/relay#2036]
### Steps to reproduce:
1.Add a tag called user_email to events, such as python:
sentry_sdk.set_tag("user_email","jon@doe.com")

2.Add the following entries as sensitive fields in the organisation privacy settings (or in the project settings)
tags
user_email
tags.user_email

Settings:
Global:
![Screenshot 2023-04-17 at 10 11 39](https://user-images.githubusercontent.com/64906376/232427919-7d465129-0e35-4218-b877-4d1fc2e46d19.png)

Project:
![Screenshot 2023-04-17 at 10 25 19](https://user-images.githubusercontent.com/64906376/232428258-501edc83-5a27-44c1-a288-807f95fa7456.png)

3.Set the project settings to use default data scrubbers.

4.Send a test event.

### Expected result:
The tag shows as `[Filtered]` by the default data scrubbers

### Actual result: 
The tag is not scrubbed:
![Screenshot 2023-04-17 at 10 11 23](https://user-images.githubusercontent.com/64906376/232428884-00096d87-d438-4f59-936e-f297da8b8632.png)

### Workaround:
Use advanced data scrubbing rules:

![Screenshot 2023-04-17 at 10 17 56](https://user-images.githubusercontent.com/64906376/232428794-127c13fd-042a-40c7-845c-fbcd3e8c32f7.png)

**Comment by jjbayer** [comment]
@rodolfoBee this is by design as far as I know. Tags are set by users deliberately, so it's up to the user what data they put there.

If they do want specific tags scrubbed, they can always add advanced rules as you describe above.

https://github.com/getsentry/relay/blob/9928da48212ae8b13fe0def866d18eae63d137d5/relay-general/src/protocol/event.rs#L440-L441

Feel free to re-open in case I missed something.
