### ISSUE TITLE
Add dry run mode to validate config

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2428]
In order to be able to detect invalid configuration before actually starting a Relay instance (e.g. in ops CI), add a validation function to the relay executable, for example

```bash
relay config --validate
```

Different parts of Relay might need to be initialized to verify that the configuration is valid. E.g. for kafka options, the configuration has to be successfully parsed and recognized by the underlying `rdkafka` lib.

An example where this went wrong can be found [here](https://github.com/getsentry/ops/pull/7746/files/4a07844ce2e411daf6e71b3be4cba10d3b62481c..8cdb03a0e6b8db95068a2dc47352c0d0a366dbb2).

**Comment by jjbayer** [comment]
cc @beezz

**Comment by jan-auer** [comment]
Additional idea: What if we distribute a tiny binary just for validation, so you don't have to pull the 200+ MB Relay image?

**Comment by Dav1dde** [comment]
We've discussed this and found a few issues with this.

Lot's of configuration can not easily be validated, this includes the Kafka configuration, some of the configuration is only known to be valid after it was sent to an external service (e.g. some Kafka values validated by the server), other values are only valid after you have actually used them (e.g. Kafka connection string/port). The next issue is, some services and config values are only accessed and initialized lazily (e.g. we may only try to open a local file once we have received data that requires writing to this file).

So while we could try to start relay and exit immediately just to see if the configuration is valid, this won't give you full confirmation that relay is going be fully operational with this configuration, it is also probably not something feasible to do in CI (since it requires connecting to actual services).

Relay fully structurally checks the configuration to be valid when loading, which detects some issues like

```yaml
processing:
  enabled: true
  kafka_config:
    - { name: "bootstrap.servers, value: "127.0.0.1:9092" }
#                               ^ Missing "
```

But unfortunately this is valid yaml:

```yaml
  kafka_config:
    - { name: bootstrap.servers", value: "127.0.0.1:9092" }
#             ^ Missing "
```

A basic config check can be done with `relay config show` which parses the config and fails if there are structural errors.


@beezz can you describe what issues you would like relay to catch and to which extent, maybe `relay config show` is already good enough or we can come up with something.

**Comment by beezz** [comment]
@Dav1dde We would like to be able to prevent failures where Relay becomes healthy for ingestion but drops events or partial failures as was the case in the incident where it can't write to some of the Kafka clusters.

**Comment by Dav1dde** [comment]
We will track, continue this in #2766.
