### ISSUE TITLE
`X-Forwarded-For` not working in SaaS

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2450]
Steps to reproduce:

Sending the following in my local dev environment:

```shell
curl -v http://localhost:8000/api/2/envelope/ \
     -H X-forwarded-for:4.4.4.4 \
    --data-binary '{"dsn":"$SENTRY_DSN"}\n{"type": "event"}\n{"user": {"ip_address": "{{auto}}"}}'
```

Results in 
![image](https://github.com/getsentry/relay/assets/1565449/f236a18d-58b1-43f1-afd0-e71e3cac1c45)

However, the same does not work for SaaS (ignores the `X-Forwarded-For` header):

```shell
curl -v https://o123.ingest.sentry.io/api/2/envelope/ \
     -H X-forwarded-for:4.4.4.4 \
    --data-binary '{"dsn":"$SENTRY_DSN"}\n{"type": "event"}\n{"user": {"ip_address": "{{auto}}"}}'
```

![image](https://github.com/getsentry/relay/assets/1565449/e35ef25c-ef91-413a-b5ef-0fc9d024f2fd)

**Comment by jjbayer** [comment]
This was an attempt to emulate a [tunnel](https://docs.sentry.io/platforms/javascript/troubleshooting/#using-the-tunnel-option) setup, as discussed here: https://github.com/getsentry/sentry-javascript/discussions/5798#discussioncomment-6867907

**Comment by jan-auer** [comment]
@beezz could we get some help on this one, please? I vaguely remember that we do not pass this header through for a reason, but I cannot find documentation on that.

Note: We need to apply the same policy to [`x-vercel-forwarded-for`](https://vercel.com/docs/edge-network/headers#x-vercel-forwarded-for)

**Comment by AbhiPrasad** [comment]
Synced offline - created an OPs ticket here for the SRE folks to investigate further. https://getsentry.atlassian.net/browse/OPS-3823

**Comment by iker-barriocanal** [comment]
We'll track this in the OPS ticket above.

**Comment by AaronFriel** [comment]
@iker-barriocanal sorry, can you keep this open until your internal tracker resolves the issue? 

I am unable to subscribe to notifications on your internal tracker, and it appears this is closed as resolved.

**Comment by IanVS** [comment]
Does that mean this hasn't been fixed yet?  I was just about to test it out.

**Comment by AbhiPrasad** [comment]
Let's re-open - I'll take care of updating with the OPs tickets.

**Comment by AbhiPrasad** [comment]
Hey, thanks for your patience everyone. We've made the changes in our SaaS infrastructure to now support `X-Forwarded-For` header. It should correctly forward the ip_address now.

We've also added support for using a proprietary header `X-Sentry-Forwarded-For` in cases where you do not want to set `X-Forwarded-For`. I will update our docs to reflect this.

**Comment by szwabodev** [comment]
Hello, sorry for bringing back an old issue, but I am having trouble with getting real user IP to save in my tunneled Sentry errors/messages while using Cloudflare as a proxy for my NextJS application. The problem is that Cloudflare replaces the "X-Forwarded-For" header with its own server IP and the real user IP is under "CF-Connecting-IP" header. I have tried using a middleware for my Sentry tunnel endpoint to replace the request's and response's "X-Forwarded-For" and "X-Vercel-Forwarder-For" as well as "X-Sentry-Forwarded-For" with the value of real user IP, however Sentry still keeps storing the cloudflare IP instead. Would it be possible to add this "[CF-Connecting-IP](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip)" as a priority header so that Sentry can automatically grab its value instead of the others if it exists? I will keep trying to replace it somehow in the middleware in the meantime, but it would be much easier if Sentry did it automatically.

**Comment by AbhiPrasad** [comment]
@szwabodev please open a new GH issue - we can take a look!

**Comment by Niaro** [comment]
@szwabodev have u opened a GH issue? could u please share the link? Im also experiencing proxy IP instead of client IP in sentry

**Comment by szwabodev** [comment]
> @szwabodev have u opened a GH issue? could u please share the link? Im also experiencing proxy IP instead of client IP in sentry

Hey, yes it was reported here: [https://github.com/getsentry/relay/issues/3493](https://github.com/getsentry/relay/issues/3493)

Looks like it should be handled already, but I just checked 2 of my latest errors from 7.113.0 SDK version and it still has cloudflare IP in user context instead of real one. I will comment on the linked issue about it.

**Comment by reyoucat** [comment]
This still looks the same.
I guess I should just put it in as a custom tag. or use`X-Sentry-Forwarded-For`

**Comment by AbhiPrasad** [comment]
@reyoucat A lot has changed since we made this fix, there could be a different root cause here. Could you open a new GitHub issue in the Sentry repo that describes your setup and why the forwarded for header is not working? https://github.com/getsentry/sentry.
