### ISSUE TITLE
Spooler handles readiness checks inconsistently when all memories are empty and maxed

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#2896]
The spooler currently handles [readiness checks](https://github.com/getsentry/relay/blob/35ea1e99729fb611a31ada617a7e49cb30ae4d2c/relay-server/src/actors/spooler/mod.rs#L910) as follows:

- In `Disk` state, the spooler reports to be ready when the disk is not full.
- In `Memory` and `MemoryFileStandby`, the spooler always reports to be ready even if the memory and disk are full.

When initialized Relay with max memory of 0 for both the memory and the disk, the buffer sees these as empty and full at the same time and will transition between `MemoryFileStandby` and `Disk` states constantly. This results in inconsistent readiness checks depending what state the buffer is in.

I'm not sure if this has broader impact, or whether this is worth fixing at all.

**Comment by olksdr** [comment]
This is partially fixed by https://github.com/getsentry/relay/pull/2949 - Relay won't switch to the memory from the disk, if the disk does not fit into the memory

Also we properly report the health of the Relay for all the modes in https://github.com/getsentry/relay/pull/2965, meaning if the Relay configured 0 for both, disk and memory, after getting the first event, Relay will become unhealthy.
