### ISSUE TITLE
Self-hosted sentry relay stops sending envelopes to sentry.io

### ISSUE THREAD

**Issue by AndriusBil** [getsentry/relay#3230]
### Self-Hosted Version

24.1.1

### CPU Architecture

amd64

### Docker Version

N/A

### Docker Compose Version

N/A

### Steps to Reproduce

1. Start relay with config:
```
    relay:
      mode: managed
      upstream: "<SENTRY_IO_URL>"
      host: 0.0.0.0
      port: 3000

    metrics:
      statsd: sentry-relay-metrics:9125
      prefix: sentry.relay
```
and credentials:
```
{
  "secret_key": "<SECRET_KEY>",
  "public_key": "<PUBLIC_KEY>",
  "id": "<UUID>"
}
```

2. Send errors and transactions to sentry-relay

### Expected Result

Expected to not stop ingesting data

### Actual Result

After about a day of running fine, starts to produce errors:
```
2024-03-04T08:58:02.151461Z ERROR relay_server::utils::managed_envelope: dropped envelope: internal error tags.has_attachments=false tags.has_sessions=true tags.has_profiles=false tags.has_transactions=false tags.has_replays=false tags.has_checkins=false tags.event_category=None cached_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 1, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 303 } recomputed_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 0, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 0 }
2024-03-04T08:58:02.151493Z ERROR relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]
```
and stops sending envelopes to sentry.io

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2117) by [Unito](https://www.unito.io)

**Comment by olksdr** [comment]
Hey @AndriusBil! 

Thanks for opening the issue. 

I have few followup question to be able to debug the problem further:
* Just to double check, that all the events are delivered to sentry.io for roughly about 24 hours? And you can see on the expected events (e.g. errors) in the UI?
* Do you have any spikes in the traffic around the time when the relay errors first appeared? 
* The full log output would be more helpful here,  before the Relay started to log errors and also would be great if you could enable `debug` [log output to](https://docs.sentry.io/product/relay/options/) maybe get more insides in what is going on. 
* Are there any firewall rules configured to control egress traffic ?

The error `envelope buffer capacity exceeded` in the endpoint means that there are many more envelopes in the memory buffer than configuration allows see `cache.envelope_buffer_size` in [docs](https://docs.sentry.io/product/relay/options/#caching). This can happen:
* when you have way too many traffic and Relay cannot process the envelopes in time
* when the upstream is blocked in your network and Relay cannot send our already processed envelope

Taking into account your initial message, it seems to me that the second reason can be the cause of the error.

**Comment by AndriusBil** [comment]
Hi @olksdr !

> Just to double check, that all the events are delivered to sentry.io for roughly about 24 hours? And you can see on the expected events (e.g. errors) in the UI?

Before the last failure it worked for 8 hours and for that duration seems that most of the envelopes were delivered to sentry.io successfully. I can see it in stats page, discover page and project pages. Then at one point it took about a minute to fill up the event queue from about 13 events to 1000.

> Do you have any spikes in the traffic around the time when the relay errors first appeared?

I don't see unusual spikes around the time the queue is filled up.

> The full log output would be more helpful here, before the Relay started to log errors and also would be great if you could enable debug [log output to](https://docs.sentry.io/product/relay/options/) maybe get more insides in what is going on.

Before and after the failure I don't see anything unusual. Some periodic errors like:
```
2024-03-04T22:58:48.432638Z ERROR relay_server::services::project: there is no project state: dropping 12 buckets tags.project_key="***"
```

Followed by periodic info like:
```
2024-03-04T23:05:50.660071Z  INFO relay_server::services::upstream: relay successfully registered with upstream
2024-03-04T23:05:50.494692Z  INFO relay_server::services::upstream: registering with upstream descriptor=https://***.sentry.io/
```

And of course thousands of messages mentioned in the description of the issue.

I'll enable debug log output and post any insights after next failure.

> Are there any firewall rules configured to control egress traffic ?

No, there is no firewall for egress

**Comment by olksdr** [comment]
This error:
``` 
2024-03-04T22:58:48.432638Z ERROR relay_server::services::project: there is no project state: dropping 12 buckets tags.project_key="***"
```
also says that your Relay instance was not able to fetch the project config from the upstream, presumable because of the slow network or high latency or general issue with networking stack (?)

Is this something you also could debug  on your side? 

You might also could try to change [some http request defaults](https://docs.sentry.io/product/relay/options/#http)

**Comment by AndriusBil** [comment]
> Is this something you also could debug on your side?

I've checked our metrics for `ProjectUpstreamCompleted` and `ProjectUpstreamFailed` counters. I see no failures for project config fetch during the time and consistently increasing completed counter.

https://github.com/getsentry/relay/blob/05e6dafa12c6b81633e43f603cf5b78508988bd1/relay-server/src/statsd.rs#L532

Are there any other metrics that I could check to narrow down the issue?

**Comment by olksdr** [comment]
You might also can monitor `UpstreamRetries` there are few tags on this metric which also could help to debug failed requests on different endpoints.

**Comment by AndriusBil** [comment]
`UpstreamRetries` shows 0 for all of the tags.

**Comment by BanallyMe** [comment]
Hi there,
we might have the same error here in our self-hosted sentry, though I'm not sure it is the same problem (we store data locally instead of sentry.io). As far as i can say it started occuring after whe upgraded from 23.12.1 to 24.2.0. I don't know if the upgrade really is the culprit though.

First reason I also thought about was too much traffic but then on the other hand we haven't had an increase of traffic lately and never had the issue before. We also can't see any unusual spikes before the issue occurs. It just seems that sentry stops working through incoming events.

Additionally to the Logs shown here we found many of these lines in the relay-log:
```shell
2024-03-04T03:43:49.321626Z ERROR relay_server::services::project_upstream: error fetching project state a6aeddd69265495eb2a1e4c301ad4ec4: deadline exceeded errors=0 pending=218 tags.did_error=false tags.was_pending=true tags.project_key=a6aeddd69265495eb2a1e4c301ad4ec4
```

Following that I found issue getsentry/self-hosted#1929 which seems to describe pretty much the problem we also see here.

As suggested, I increased cache.envelope_buffer_size to 1000000, which increased the span of time until sentry stopped working. Using the default value it takes just about 6 hours until it stops working, with the increased value it worked for about a week until stopping again.

Following suggestions in 1929 I checked the length of redis keys `relay_config` and `relay_config_bulk` to find that the key `relay_config` keeps increasing pretty fast when the problem is ongoing (I found a length of about 4kk here). After restarting sentry the value will start decreasing again. `relay_config_bulk` stays at 0. So it seems there is a celery task not working properly anymore.

**Comment by AndriusBil** [comment]
@olksdr 
Experienced the same failure yesterday. This time with the debug logs enabled. What messages should I be looking for in debug logs to narrow down the issue?

**Comment by olksdr** [comment]
As I mentioned above, could you provide the logs here, it would be easier to help debugging the issue, and spot the problem if there are any present in the logs. 
All the project keys and other IDs can be removed

**Comment by olksdr** [comment]
The rollback to `23.12.1` seems to help for now. 

**TODO**: 
* check what the differences between those releases

**Comment by olksdr** [comment]
Changes between the releases:
https://github.com/getsentry/relay/compare/23.12.1...24.1.1

**Comment by olksdr** [comment]
Related to https://github.com/getsentry/team-ingest/issues/297
And will be worked on within https://github.com/getsentry/team-ingest/issues/345

**Comment by mvarendorff2** [comment]
@olksdr since the linked repo is private, is there any chance you can update this issue when the issue is fixed "upstream"? We are facing this problem in a fully self-hosted instance as well with its own upstream and a quick heads-up would really help sorting out the update as quickly as possible once its available!

**Comment by olksdr** [comment]
@mvarendorff  I will update this issue once the fix is in.
