### ISSUE TITLE
Memory watermark in readiness probe never recovers, causing relay outage

### ISSUE THREAD

**Issue by zeeZ** [getsentry/relay#3874]
https://github.com/getsentry/relay/issues/2880 introduced a memory watermark to **readiness** endpoint. In situations where not enough memory can be freed, the relay will be stuck in this state indefinitely.

In Kubernetes there is no mechanism to automatically recover a pod stuck with a failing readiness probe, so eventually all pods will reach this state, causing an outage and requiring manual intervention. This is worse than the occasional OOM kill (which still happen anyway).

My current workaround is to set the undocumented `health.max_memory_percent` to `1.0`. Increasing it from the default 95% to 98% only delayed the inevitable a bit.

**Comment by jjbayer** [comment]
@zeeZ thanks for reporting this! We have the health check because in our production environment, we assume that Relay automatically frees memory by processing events. If this does not happen in your case, do you know why? It might be that Relay was provisioned with too little RAM to begin with.

Other from that, it sounds like everything works as expected -- you don't want Relay to go into the unhealthy state when it's low on memory, so you raised the threshold to 1.0.

**Comment by zeeZ** [comment]
It's running in a memory constrained environment of 512MB, yes. This happens even when only handling errors with relatively small envelopes and an aggressive spooling config though. Usage jumps by about 100MB even when there is no requests and then never recovers even though the connection to Sentry (self-hosted) is stable.

Regardless, I think there should be a deadline when the watermark goes from not ready to not healthy if all current/no new events were processed and enough memory still isn't available.

**Comment by jjbayer** [comment]
> I think there should be a deadline when the watermark goes from not ready to not healthy if all current/no new events were processed and enough memory still isn't available.

Ah, you're saying Relay should fail both the liveness probe and the readiness probe in such cases. But then kubernetes would replace the pod with one that would probably run into memory issues again. So it seems to me the temporary solution here is giving Relay more memory. Or, if that's not possible, disable the health check like you did.

The real solution would be to make Relay consume less memory in the first place, we have an open issue for that: https://github.com/getsentry/relay/issues/3021.

**Comment by zeeZ** [comment]
> Ah, you're saying Relay should fail both the liveness probe and the readiness probe in such cases. But then kubernetes would replace the pod with one that would probably run into memory issues again.

Yes. Setting aside my specific context and speaking generally, I believe crashlooping is better than perpetual unready. There are no external dependencies that can be fixed, so the only thing a person would be able to do is manually restart the service.

In case of a slow memory leak, that pod would eventually run out of memory and be restarted again, maybe losing a few unprocessed events or a temporary outage in case all pods run out of memory at the same time, but the alternative is that eventually all pods become unready and no further events are processed until manual intervention.

**Comment by Dav1dde** [comment]
> Setting aside my specific context and speaking generally, I believe crashlooping is better than perpetual unready. 

We specifically added this because unready is better than crashlooping, because it does not lose data. 

> There are no external dependencies that can be fixed, so the only thing a person would be able to do is manually restart the service.

The most common case for this failure is an unhealthy Sentry or Redis, both of these can be fixed.

You already found the setting to disable the behaviour if it doesn't work for you. But you're also running Relay massively underprovisioned. The[ minimum recommendation is 2 gigabytes of RAM](https://docs.sentry.io/product/relay/operating-guidelines/#system-requirements-and-recommendations) at the moment.

**Comment by jjbayer** [comment]
@zeeZ closing this as you seem to have found a solution for your use case, and we are not planning to change Relay's behavior.
