### ISSUE TITLE
TransactionsProcessor modifies event timestamps by default

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/relay#535]
`TransactionsProcessor` modifies event timestamps by default as part of a "clock drift detection" feature.

Disabling it requires setting a value on the `now` field. None of this is documented.

The behavior is surprising, and makes constructing tests and generally using `TransactionsProcessor` unnecessarily hard, requiring deep knowledge on the implementation details.

**Comment by untitaker** [comment]
I don't really understand what you're proposing. Is this only about testability or do you want SDKs to opt into clock-correcting behavior?

**Comment by untitaker** [comment]
[answered in slack, no SDK API change]

I think we could write a dedicated processor for timestamp correction and also run it for error events. There is also some logic for fixing timestamps in the store processor for regular events, although the logic is a different one. I wonder if it would make sense to merge those two

**Comment by rhcarvalho** [comment]
Either at least the behavior is documented, or best, code is explicit about what is going to happen:

```diff
- TransactionsProcessor::new(None)
+ TransactionsProcessor::new(None, applyTimestampCorrection=true) // with whatever syntax makes sense
```

Setting `TransactionsProcessor.now` is not obvious, and the documented purpose of this field doesn't describe its influence on mutation of timestamps.

**Comment by jan-auer** [comment]
+1 on creating a separate processor (or a function called from the regular store normalizer). This seems to align most with the design decisions around orthogonal concerns in processors.

**Comment by jan-auer** [comment]
One more argument to make this a separate processor: We likely also want external Relays to run this in non-processing mode. The reasoning is:

- External Relays can be trusted sufficiently with having an accurate clock.
- They are much closer to the source, meaning the drift can be detected more accurately
- Since Relays can incur arbitrary networking delays when forwarding through remote regions, the next hop should no longer apply drift correction because every time we correct, we actually shift a little bit. 

This also ties in with the argument in #534 to remove `sent_at` and not normalize when it's missing.
