### ISSUE TITLE
Docker image semver tags

### ISSUE THREAD

**Issue by fmartinou** [getsentry/relay#557]
Hi,

I'm looking for a 0.4.x Relay image to test relay with an on-premise Sentry 10 install and I realized that there are no semver tags on your images (neither on the Docker hub nor on the GCP registry); just UUIDs...

How can I find a specific version?

**Comment by jan-auer** [comment]
The easiest way would be to get the commit hash from the release you want to run and use that as docker tag. 

We're in the final stage of integrating Relay into the onprem setup and will release a new version as soon as this is complete. That would allow you to use the latest released version of Relay. We'll look into tagging releases in Docker.

**Comment by fmartinou** [comment]
Thanks for your answer.

2 quick questions:
- which Relay version do I need to integrate to a Sentry 10 version at this time?
- when is planned the "official" Relay version compatible with onprem Sentry10?

Because the oldest tag available in the GCP registry is pointing to a `0.4.65` version and it's not working;
I get a 400 error from sentry when Relay sends the event.
I think I encounter the same issue as [this one](https://github.com/getsentry/relay/issues/473)

I'd like to test the ` 0.4.46` version but sadly it's not available in the registry anymore.

**Comment by jan-auer** [comment]
> Which Relay version do I need to integrate to a Sentry 10 version at this time?

That would be version 0.4.61 or older. To be honest, I was not aware that GCP removes old tags. This should definitely not have happend, and we'll look into restoring those tags, or moving it over to Dockerhub going forward. 

As a workaround, you could try to build the container yourself by checking out https://github.com/getsentry/relay/commit/0cca2b1854d6956326719809d9a0579df6a9bb13 and running `docker build` inside the root folder. This should still work, or otherwise I could look into creating a temporary branch that does.

> when is planned the "official" Relay version compatible with onprem Sentry10?

All implementation work for this has been completed at this point, but we are still finishing the integration into our onpremise setup. I expect some movement on this next week, and might be able to communicate a timeline then. 

cc @BYK @tonyo

**Comment by tonyo** [comment]
We don't have semver tags on Relay Docker images (yet), but neither Google Container Registry nor Dockerhub shouldn't delete old tags.

One caveat is that we renamed this project (from `semaphore` to `relay`) along with the Docker image a couple of months ago, so that's why some older tags might be missing from the `relay` image.

So to answer your question @fmartinou, as @jan-auer suggested, you can take the full SHA tag of the version you need (https://github.com/getsentry/relay/commit/0cca2b1854d6956326719809d9a0579df6a9bb13), but use the older name (`semaphore`).

So this should work:
```
docker pull us.gcr.io/sentryio/semaphore:0cca2b1854d6956326719809d9a0579df6a9bb13
```

**Comment by fmartinou** [comment]
Thank you @tonyo and @jan-auer for your answers.
I didn't know about this old name; I'll give it a try... thanks !

**Comment by BYK** [comment]
2 cents: I strongly recommend pulling from Docker Hub in the future though :)
